//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achievement
    {
        public int AchievementID { get; set; }
        public string AchievementDescription { get; set; }
        public bool Isactive { get; set; }
        public string ImageName { get; set; }
        public Nullable<int> Order { get; set; }
        public byte UIDAdd { get; set; }
        public System.DateTime AddDate { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
        public string AchievementTitle { get; set; }
    }
}
