//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class AcOpeningBalance
    {
        public int AcCode { get; set; }
        public byte BranchId { get; set; }
        public Nullable<decimal> OpBalance { get; set; }
    }
}
