//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssignmentMasterHistory
    {
        public int HistoryID { get; set; }
        public int AssignmentID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string AssignmentName { get; set; }
        public string AssignmentDescription { get; set; }
        public Nullable<int> AssignBy { get; set; }
        public Nullable<System.DateTime> AssignDate { get; set; }
        public Nullable<System.DateTime> SubmissionDate { get; set; }
        public Nullable<int> SessionID { get; set; }
        public string MasterRemark { get; set; }
        public Nullable<byte> UIDAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> UIDMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<byte> ChangedBy { get; set; }
        public System.DateTime ChangedDate { get; set; }
        public bool IsDeleted { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
    }
}
