//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusMasterHistory
    {
        public int HistoryID { get; set; }
        public int BusID { get; set; }
        public int BusNo { get; set; }
        public string LorryNo { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string MobileNo { get; set; }
        public string EngineNo { get; set; }
        public string ChassisNo { get; set; }
        public Nullable<System.DateTime> PassDate { get; set; }
        public string RTOPass { get; set; }
        public bool IsSelf { get; set; }
        public string MfgCompany { get; set; }
        public string MfgYear { get; set; }
        public string MakeNo { get; set; }
        public string Model { get; set; }
        public string Colour { get; set; }
        public string VehicleClass { get; set; }
        public string RTOCardNo { get; set; }
        public Nullable<System.DateTime> InsuranceDate { get; set; }
        public string RTOName { get; set; }
        public Nullable<decimal> RTOPassedWeight { get; set; }
        public Nullable<System.DateTime> RegValidDate { get; set; }
        public Nullable<decimal> OpeningBalance { get; set; }
        public Nullable<int> OpeningKM { get; set; }
        public Nullable<byte> UIDAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> UIDMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<byte> ChangedBy { get; set; }
        public System.DateTime ChangedDate { get; set; }
        public bool IsDeleted { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
    }
}
