//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSetup
    {
        public int ClassSetupID { get; set; }
        public string ClassDescription { get; set; }
        public int ClassID { get; set; }
        public Nullable<int> ClassCategoryID { get; set; }
        public int SectionID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<byte> UIDAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> UIDMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<byte> CompID { get; set; }
        public Nullable<byte> BranchID { get; set; }
        public Nullable<int> ClassTeacherID { get; set; }
        public Nullable<int> ClassTeacherSubjectID { get; set; }
        public Nullable<int> WorkingDayPerWeek { get; set; }
        public Nullable<int> PeriodsPerDay { get; set; }
        public Nullable<int> Recess1PerWeek { get; set; }
        public Nullable<int> Recess2PerWeek { get; set; }
        public Nullable<int> WingId { get; set; }
    }
}
