//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClassSetupHistory
    {
        public int ID { get; set; }
        public int ClassSetupID { get; set; }
        public string ClassDescription { get; set; }
        public int ClassID { get; set; }
        public Nullable<int> ClassCategoryID { get; set; }
        public int SectionID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<byte> UIDAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> UIDMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<byte> ChangedBy { get; set; }
        public System.DateTime ChangedDate { get; set; }
        public bool IsDeleted { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
    }
}
