//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverMaster
    {
        public string Dname { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public string Licence { get; set; }
        public Nullable<System.DateTime> Validupto { get; set; }
        public string RTO { get; set; }
        public string LorryNo { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
        public Nullable<bool> uploadflag { get; set; }
        public string PAN { get; set; }
        public int DriverId { get; set; }
        public Nullable<int> StateId { get; set; }
        public Nullable<int> CityID { get; set; }
        public string PinCode { get; set; }
        public string DrMobileNo { get; set; }
        public string DrMobileNo2 { get; set; }
        public string Remark { get; set; }
        public string EmpType { get; set; }
        public string DrEmailID { get; set; }
        public string RefBy { get; set; }
        public string RefMobileNo { get; set; }
        public string RefAddress { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public Nullable<int> UIDAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> UIDMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public string Gender { get; set; }
    }
}
