//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpGradeAllotmentDetail
    {
        public int ID { get; set; }
        public int AllotmentID { get; set; }
        public Nullable<int> AllowanceDeductionID { get; set; }
        public string AllowanceDeductionType { get; set; }
        public string RateType { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public string AllowanceDeductionName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
    }
}
