//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeAttendance
    {
        public int AttendanceLogId { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<System.DateTime> AttendanceDate { get; set; }
        public Nullable<decimal> Duration { get; set; }
        public string InTime { get; set; }
        public string OutTime { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<decimal> Present { get; set; }
        public Nullable<decimal> Absent { get; set; }
        public string Status { get; set; }
        public string StatusCode { get; set; }
        public string PunchRecords { get; set; }
        public string Remark { get; set; }
        public int SessionID { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> UIDAdd { get; set; }
        public string TimeStatus { get; set; }
    }
}
