//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeLeavesYearly
    {
        public int EmpID { get; set; }
        public Nullable<int> ML { get; set; }
        public Nullable<int> CL { get; set; }
        public Nullable<int> EL { get; set; }
        public Nullable<int> HPL { get; set; }
        public Nullable<int> OPL { get; set; }
        public Nullable<byte> UIDAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> UIDMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
        public int SessionID { get; set; }
    }
}
