//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamQuestionAnswerMaster
    {
        public int QuestionAnswerID { get; set; }
        public Nullable<int> ExamID { get; set; }
        public Nullable<int> SubExamID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> SubjectID1 { get; set; }
        public Nullable<int> SubjectID2 { get; set; }
        public Nullable<int> SubjectID3 { get; set; }
        public Nullable<int> QuestionType { get; set; }
        public Nullable<int> OptRequired { get; set; }
        public string Question { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Option4 { get; set; }
        public Nullable<int> AnswerObjective { get; set; }
        public string AnswerDscriptive { get; set; }
        public Nullable<int> Marks { get; set; }
        public bool IsQuestionImage { get; set; }
        public string QuestionImage { get; set; }
        public string AnswerImage { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<int> UIDAdd { get; set; }
        public Nullable<int> UIDMod { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> CompID { get; set; }
        public Nullable<byte> BranchID { get; set; }
    }
}
