//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeesVoucherMaster
    {
        public int VoucherID { get; set; }
        public Nullable<int> FeesVoucherNo { get; set; }
        public Nullable<int> AcccountCode { get; set; }
        public Nullable<System.DateTime> VoucherDate { get; set; }
        public Nullable<int> StudentID { get; set; }
        public string StudentName { get; set; }
        public bool IsRegistered { get; set; }
        public string Narration { get; set; }
        public Nullable<byte> CompId { get; set; }
        public Nullable<byte> BranchID { get; set; }
        public Nullable<byte> SessionID { get; set; }
        public Nullable<byte> UIdAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> UIdMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    }
}
