//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeesHead
    {
        public int FeesHeadID { get; set; }
        public string FeesHeadName { get; set; }
        public string PrintHeadName { get; set; }
        public Nullable<bool> ISRebate { get; set; }
        public Nullable<int> Accode { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string FeesHeadType { get; set; }
        public decimal DefaultAmount { get; set; }
        public Nullable<byte> UIDAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> UIDMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
    }
}
