//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeeTerm
    {
        public int ID { get; set; }
        public int FeeTermID { get; set; }
        public string FeeTermName { get; set; }
        public string FeeTermType { get; set; }
        public System.DateTime FeeTermFromDate { get; set; }
        public System.DateTime FeeTermToDate { get; set; }
        public Nullable<decimal> FineAmount { get; set; }
        public Nullable<byte> SessionId { get; set; }
        public Nullable<byte> UIDAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> UIDMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
    }
}
