//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlyerVoiceMaster
    {
        public int FlyerVoiceID { get; set; }
        public string FlyerVoiceName { get; set; }
        public string FlyerVoicePath { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> Isactive { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
    }
}
