//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class GoDown
    {
        public byte CompID { get; set; }
        public byte GodownID { get; set; }
        public byte BranchID { get; set; }
        public string GodownName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Stationery { get; set; }
        public Nullable<decimal> OpBalance { get; set; }
        public string ShortName { get; set; }
    }
}
