//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomePageRolePermission
    {
        public int HomePageID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public int ModuleID { get; set; }
        public int FeatureID { get; set; }
        public bool CanView { get; set; }
        public int FeatureOrder { get; set; }
        public int CompID { get; set; }
        public int BranchID { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public bool IsOnlyModuleRequire { get; set; }
    }
}
