//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemLedgerDetail
    {
        public int ID { get; set; }
        public int TransNo { get; set; }
        public string TransType { get; set; }
        public int ItemID { get; set; }
        public string Packing { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string TaxName { get; set; }
        public Nullable<decimal> TaxPercent { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public string Remark { get; set; }
        public Nullable<int> SessionID { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
    }
}
