//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemLedgerMaster
    {
        public int TransNo { get; set; }
        public Nullable<System.DateTime> TransDate { get; set; }
        public string TransType { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public string ChallanNo { get; set; }
        public Nullable<System.DateTime> ChallanDate { get; set; }
        public string PONo { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public Nullable<int> SupplierID { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
        public Nullable<decimal> TaxAmount { get; set; }
        public Nullable<decimal> BillAmount { get; set; }
        public Nullable<decimal> Discount { get; set; }
        public Nullable<decimal> Labour { get; set; }
        public Nullable<decimal> Cartage { get; set; }
        public Nullable<decimal> Freight { get; set; }
        public Nullable<decimal> Other { get; set; }
        public Nullable<decimal> PackingCharge { get; set; }
        public Nullable<decimal> NetAmount { get; set; }
        public string FormNo { get; set; }
        public string OrderedBy { get; set; }
        public string ReceivedBy { get; set; }
        public string Remark { get; set; }
        public Nullable<int> SessionID { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
        public Nullable<byte> UIdAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> UIdMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
    }
}
