//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemAllotmentDetail
    {
        public int ID { get; set; }
        public int AllotmentID { get; set; }
        public Nullable<int> ItemID { get; set; }
        public Nullable<decimal> Qty { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
        public Nullable<int> SessionID { get; set; }
    }
}
