//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ledger
    {
        public long TID { get; set; }
        public Nullable<byte> SessionID { get; set; }
        public Nullable<long> TransNo { get; set; }
        public Nullable<int> VouNo { get; set; }
        public Nullable<System.DateTime> VouDate { get; set; }
        public string Type { get; set; }
        public string VouType { get; set; }
        public string VouMode { get; set; }
        public Nullable<short> Sno { get; set; }
        public Nullable<int> AcCode { get; set; }
        public string Narration { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> ChqNo { get; set; }
        public Nullable<System.DateTime> ChqDate { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public Nullable<byte> UIdAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> UIdMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
    }
}
