//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class LetterHeadMaster
    {
        public int LetterHeadID { get; set; }
        public string LetterHeadName { get; set; }
        public string LetterHeadDesc { get; set; }
        public bool IsActive { get; set; }
        public Nullable<System.DateTime> LetterHeadDate { get; set; }
        public Nullable<int> LetterHeadOrder { get; set; }
        public Nullable<System.DateTime> FromDate { get; set; }
        public Nullable<System.DateTime> ToDate { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
        public string LetterHeadDesc2 { get; set; }
        public string LetterHeadDesc3 { get; set; }
        public byte[] LHeadBinaryImage { get; set; }
        public string ImageName { get; set; }
    }
}
