//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lib_BookDetail
    {
        public int BookId { get; set; }
        public int AccessionId { get; set; }
        public Nullable<int> BookNo { get; set; }
        public string Edition { get; set; }
        public Nullable<int> PublishYear { get; set; }
        public Nullable<int> Pages { get; set; }
        public Nullable<decimal> Price { get; set; }
        public byte[] FrontCover { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<int> ShelfId { get; set; }
        public Nullable<int> RackId { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<bool> IsDamaged { get; set; }
        public Nullable<bool> IsLost { get; set; }
        public Nullable<int> DamagedBy { get; set; }
        public Nullable<System.DateTime> DamageDate { get; set; }
        public string DamageRemark { get; set; }
        public Nullable<int> LostBy { get; set; }
        public Nullable<System.DateTime> LostDate { get; set; }
        public string LostRemark { get; set; }
        public string MemberType { get; set; }
        public Nullable<bool> Issuable { get; set; }
        public string CallNo { get; set; }
        public string FrontCoverImage { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
    }
}
