//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lib_BookMaster
    {
        public int AccessionId { get; set; }
        public string AccessionNo { get; set; }
        public string BookTitle { get; set; }
        public string Author1 { get; set; }
        public string Author2 { get; set; }
        public string Author3 { get; set; }
        public string Author4 { get; set; }
        public string GrantedBy { get; set; }
        public string Publisher { get; set; }
        public Nullable<int> Volume { get; set; }
        public string Medium { get; set; }
        public string Source { get; set; }
        public string WebUrl { get; set; }
        public string ISBNNo { get; set; }
        public string ISSNNo { get; set; }
        public string ClassificationNo { get; set; }
        public string Subject { get; set; }
        public Nullable<byte> UIDAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> UIDMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
    }
}
