//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlinePortalLogin
    {
        public int LoginID { get; set; }
        public Nullable<int> LoginUserID { get; set; }
        public Nullable<int> LoginUSerType { get; set; }
        public Nullable<System.DateTime> LoginDateTime { get; set; }
        public Nullable<System.DateTime> LogoutDateTime { get; set; }
        public string LoginIPAdress { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<int> CompID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public Nullable<int> SessionID { get; set; }
    }
}
