//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class OnlineNotification
    {
        public int NoticeID { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public int CompID { get; set; }
        public int BranchID { get; set; }
        public int ClassID { get; set; }
        public int SessionId { get; set; }
        public string Message_id { get; set; }
        public bool NotificationStatus { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<int> NotificationFor { get; set; }
        public Nullable<bool> IsAllClass { get; set; }
    }
}
