//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class OwnerMaster
    {
        public int OwnerID { get; set; }
        public string OwnerName { get; set; }
        public string FatherName { get; set; }
        public string CompanyName { get; set; }
        public string LocalAddress { get; set; }
        public string permanentAddress { get; set; }
        public string BloodGroup { get; set; }
        public string City { get; set; }
        public string PinCode { get; set; }
        public string PhoneNo { get; set; }
        public string MobileNo1 { get; set; }
        public string MobileNo2 { get; set; }
        public string PanNo { get; set; }
        public string FaxNo { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string EmailID { get; set; }
        public string Remark { get; set; }
        public Nullable<byte> UIDAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> UIDMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
    }
}
