//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ParentLogin
    {
        public int parentLoginID { get; set; }
        public int StudentID { get; set; }
        public string ParentName { get; set; }
        public string ParentUserName { get; set; }
        public string Password { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
    }
}
