//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class PayBillDetail
    {
        public int ID { get; set; }
        public int BillNo { get; set; }
        public int EmpID { get; set; }
        public Nullable<decimal> BasicPay { get; set; }
        public Nullable<decimal> Allowance { get; set; }
        public Nullable<decimal> Deduction { get; set; }
        public Nullable<decimal> AbsentAmt { get; set; }
        public Nullable<decimal> NetPay { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
        public Nullable<int> SessionID { get; set; }
    }
}
