//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoGalleryMaster
    {
        public int GalleryID { get; set; }
        public string FolderName { get; set; }
        public string PathName { get; set; }
        public string EventName { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> EventDate { get; set; }
        public Nullable<System.DateTime> Fromdate { get; set; }
        public Nullable<System.DateTime> Todate { get; set; }
        public Nullable<int> GalleryOrder { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<byte> BranchID { get; set; }
        public Nullable<byte> CompID { get; set; }
    }
}
