//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhotoGalleryDetail
    {
        public int GalleryDetailID { get; set; }
        public int GalleryID { get; set; }
        public string PhotoName { get; set; }
        public Nullable<int> PhotoOrder { get; set; }
        public bool IsActive { get; set; }
    }
}
