//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestMaster
    {
        public int RequestID { get; set; }
        public int SendByID { get; set; }
        public string SendByType { get; set; }
        public string Request { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public bool ReceiveFlage { get; set; }
        public string Reply { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
    }
}
