//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SchoolMaster
    {
        public int SchoolID { get; set; }
        public string RegistrationNo { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public string SchoolName { get; set; }
        public string SchollerNo { get; set; }
        public string UniqueID { get; set; }
        public byte[] Logo { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PhoneNo1 { get; set; }
        public string PhoneNo2 { get; set; }
        public string EmailID { get; set; }
        public string Remark { get; set; }
        public bool BusFacility { get; set; }
        public bool HostelFacility { get; set; }
        public bool MessFacility { get; set; }
        public Nullable<bool> DaywiseAccounting { get; set; }
        public Nullable<bool> FeesAccounting { get; set; }
        public byte CompID { get; set; }
        public byte BranchId { get; set; }
        public string Thought { get; set; }
        public bool IsAdminSMSCopy { get; set; }
        public string AdminSMSCopyNo { get; set; }
        public string ShortName { get; set; }
    }
}
