//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SetExam
    {
        public int ExamID { get; set; }
        public Nullable<int> ExamCategoryID { get; set; }
        public Nullable<int> ClassSetID { get; set; }
        public Nullable<int> SubjectID { get; set; }
        public string MaxMarks { get; set; }
        public string PassMarks { get; set; }
        public Nullable<System.DateTime> ExamDate { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> SessionID { get; set; }
    }
}
