//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SettingMaster
    {
        public int SettingID { get; set; }
        public bool IncludeNameInSMS { get; set; }
        public bool SaveSMSLog { get; set; }
        public bool ManageHistory { get; set; }
        public byte CompID { get; set; }
        public byte BranchId { get; set; }
        public Nullable<System.DateTime> FeeLastDate { get; set; }
        public string AppDomainName { get; set; }
        public string StudentDomainName { get; set; }
        public string TeacherDomainName { get; set; }
        public string ParentDomainName { get; set; }
        public string PR_EmailID { get; set; }
        public string PR_Password { get; set; }
        public string PR_Host { get; set; }
        public Nullable<int> PR_Port { get; set; }
        public bool IsSMS_Facility { get; set; }
        public string ApiMerchantKey { get; set; }
        public string ApiMerchantSalt { get; set; }
        public string ApiAccountID { get; set; }
        public string SMSUserID { get; set; }
        public string SMSPassword { get; set; }
        public string SMSSenderID { get; set; }
        public string SMSAPIKey { get; set; }
        public string FtpUrl { get; set; }
        public string FtpUID { get; set; }
        public string FtpPassword { get; set; }
        public string FtpDefaultFolder { get; set; }
    }
}
