//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SmartClassMachineValidatation
    {
        public int Id { get; set; }
        public string MacAdd { get; set; }
        public string MachineIP { get; set; }
        public bool Status { get; set; }
        public byte CompID { get; set; }
    }
}
