//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSLogDetail
    {
        public int SMSDetailID { get; set; }
        public int SMSLogID { get; set; }
        public int StudentID { get; set; }
        public string MobileNo { get; set; }
        public string SMSText { get; set; }
        public int SessionID { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
    }
}
