//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SMSLogMaster
    {
        public int SMSLogID { get; set; }
        public Nullable<System.DateTime> SentDateTime { get; set; }
        public string SMSText { get; set; }
        public string SMSMobileNo { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public Nullable<byte> SessionID { get; set; }
        public Nullable<int> UIdAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public string SMSModal { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
    }
}
