//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFeesMasterHistory
    {
        public int HistoryID { get; set; }
        public int StudmasterID { get; set; }
        public string Type { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> TermID { get; set; }
        public Nullable<int> FeesTransactionID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string VoucharNo { get; set; }
        public Nullable<System.DateTime> VoucharDate { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<byte> UIDAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> UIDMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<int> StudentClassId { get; set; }
        public bool PaidFlag { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public Nullable<decimal> DiscountRate { get; set; }
        public Nullable<byte> ChangedBy { get; set; }
        public System.DateTime ChangedDate { get; set; }
        public bool IsDeleted { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
    }
}
