//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentDocumentDetailHistory
    {
        public int HistoryID { get; set; }
        public int StudDocID { get; set; }
        public int StudentID { get; set; }
        public string DocumentName { get; set; }
        public string FileName { get; set; }
        public string Remark { get; set; }
        public Nullable<int> UIDAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> UIDMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<byte> ChangedBy { get; set; }
        public System.DateTime ChangedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> SessionID { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
    }
}
