//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentVisitor
    {
        public int VisitorID { get; set; }
        public string VisitorName { get; set; }
        public string RelationShip { get; set; }
        public int StudentID { get; set; }
        public Nullable<int> ClassSetupID { get; set; }
        public string VisitorImage { get; set; }
        public Nullable<System.DateTime> VisitDate { get; set; }
        public string VisitTime { get; set; }
        public string VisitorMobileNo { get; set; }
        public string VisitorAddress { get; set; }
        public string Remark { get; set; }
        public int SessionID { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
        public Nullable<int> UIDAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> UIDMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
    }
}
