//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentFeesDetail
    {
        public int StudentDetailID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> TermID { get; set; }
        public Nullable<int> HeadID { get; set; }
        public string Type { get; set; }
        public Nullable<int> StudentClassId { get; set; }
        public Nullable<int> StudMasterId { get; set; }
        public Nullable<decimal> HeadAmount { get; set; }
        public Nullable<int> SessionId { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
    }
}
