//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentLeaveApplicationHistory
    {
        public int HistoryID { get; set; }
        public int LeaveID { get; set; }
        public int StudentID { get; set; }
        public string LeaveName { get; set; }
        public Nullable<System.DateTime> LeaveFromDate { get; set; }
        public string LeaveFromType { get; set; }
        public Nullable<System.DateTime> LeaveToDate { get; set; }
        public string LeaveToType { get; set; }
        public Nullable<int> TotalDay { get; set; }
        public string Reason { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public string TeacherStatus { get; set; }
        public string TeacherRemark { get; set; }
        public string AdminStatus { get; set; }
        public string AdminRemark { get; set; }
        public int SessionID { get; set; }
        public Nullable<byte> UIDAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> UIDMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<byte> ChangedBy { get; set; }
        public System.DateTime ChangedDate { get; set; }
        public bool IsDeleted { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
    }
}
