//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSession
    {
        public int StudentSessionID { get; set; }
        public int StudentID { get; set; }
        public int ClassSetupID { get; set; }
        public int SessionID { get; set; }
        public int ClassID { get; set; }
        public Nullable<int> HouseID { get; set; }
        public bool HostelFacility { get; set; }
        public bool BusFacility { get; set; }
        public Nullable<int> BusID { get; set; }
        public bool SMSInHindi { get; set; }
        public Nullable<byte> UIDAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> UIDMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public bool FeesStructStatus { get; set; }
        public bool IsNewStudent { get; set; }
        public Nullable<int> RollNo { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
        public bool IsTransfered { get; set; }
        public string Rank { get; set; }
        public string Rank1 { get; set; }
        public string Rank2 { get; set; }
        public string Rank3 { get; set; }
        public string OverallRank { get; set; }
    }
}
