//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentPreviousDetail
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public string PreviousSchoolName { get; set; }
        public Nullable<System.DateTime> DateOfLeaving { get; set; }
        public string PreviousClass { get; set; }
        public string ExamResult { get; set; }
        public string PreviousDetailRemark { get; set; }
        public Nullable<int> UIDAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> UIDMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public int SessionID { get; set; }
        public Nullable<byte> CompID { get; set; }
        public Nullable<byte> BranchID { get; set; }
    }
}
