//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentSiblingDetail
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public string Relation { get; set; }
        public string SchoolName { get; set; }
        public string Class { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public Nullable<byte> Age { get; set; }
    }
}
