//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentRegistrationHistory
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public string EnrollmentNo { get; set; }
        public Nullable<System.DateTime> EnrollmentDate { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string ICardNo { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string City { get; set; }
        public string Nationality { get; set; }
        public string MotherTounge { get; set; }
        public Nullable<int> ClassID { get; set; }
        public string LocalAddress { get; set; }
        public string ParmanentAddress { get; set; }
        public string Caste { get; set; }
        public string BloodGroup { get; set; }
        public string Religion { get; set; }
        public bool TransportRequired { get; set; }
        public bool HostelRequired { get; set; }
        public bool EnableSMSFeature { get; set; }
        public bool TCGiven { get; set; }
        public string TCNumber { get; set; }
        public Nullable<System.DateTime> TCDate { get; set; }
        public string CasteCategory { get; set; }
        public byte[] StudentPhoto { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string FQualification { get; set; }
        public string MQualification { get; set; }
        public string FatherMobileNo { get; set; }
        public string MotherMobileNo { get; set; }
        public string FOccupation { get; set; }
        public string MOccupation { get; set; }
        public Nullable<System.DateTime> FatherDOB { get; set; }
        public Nullable<System.DateTime> MotherDOB { get; set; }
        public Nullable<decimal> FIncome { get; set; }
        public Nullable<decimal> MIncome { get; set; }
        public string FOfficeAddress { get; set; }
        public string MOfficeAddress { get; set; }
        public string FatherEmailID { get; set; }
        public string MotherEmailID { get; set; }
        public string FOfficePhoneNo { get; set; }
        public string MOfficePhoneNo { get; set; }
        public string HomePhoneNo { get; set; }
        public string GuardianName { get; set; }
        public string GOccupation { get; set; }
        public string Relationship { get; set; }
        public string GAddress { get; set; }
        public string GEmailID { get; set; }
        public string GMobileNo { get; set; }
        public string GPhoneNo { get; set; }
        public string SMSMobileNo { get; set; }
        public Nullable<System.DateTime> AnniversaryDate { get; set; }
        public Nullable<byte> UIDAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> UIDMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public byte[] AppImage { get; set; }
        public string AppImageName { get; set; }
        public int SessionID { get; set; }
        public Nullable<byte> ChangedBy { get; set; }
        public Nullable<System.DateTime> ChangedDate { get; set; }
        public bool IsDeleted { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
    }
}
