//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubtitutionMaster
    {
        public int SubstitutionID { get; set; }
        public bool AnySubjectTeacherinWholeSchool { get; set; }
        public bool SameWingWithAnySubjectTeacher { get; set; }
        public bool SameWingWithSameSubjectTeacher { get; set; }
        public bool SameClassWithAnySubjectTeacher { get; set; }
        public bool IsRepeatTeacherInSubstitution { get; set; }
        public Nullable<byte> SessionID { get; set; }
        public Nullable<byte> CompID { get; set; }
        public Nullable<byte> BranchID { get; set; }
        public Nullable<byte> UIDAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> UIDMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
    }
}
