//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeacherQualification
    {
        public int ID { get; set; }
        public int TeacherID { get; set; }
        public string DegreeName { get; set; }
        public Nullable<int> YearOfPassing { get; set; }
        public string Percentage { get; set; }
        public string University { get; set; }
        public Nullable<int> UIDAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<int> UIDMod { get; set; }
        public Nullable<System.DateTime> ModeDate { get; set; }
        public Nullable<int> SessionID { get; set; }
        public byte CompID { get; set; }
        public byte BranchId { get; set; }
    }
}
