//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTableTeacherSetting
    {
        public int SID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public string TeacherName { get; set; }
        public string ShortName { get; set; }
        public string Qualification { get; set; }
        public string Gender { get; set; }
        public string MaxPeriod { get; set; }
        public Nullable<int> Uploaded { get; set; }
        public Nullable<int> Active { get; set; }
        public Nullable<int> FreePeriods { get; set; }
        public Nullable<bool> IsSubstitute { get; set; }
        public Nullable<int> WingID { get; set; }
        public Nullable<byte> BranchID { get; set; }
        public Nullable<byte> SessionID { get; set; }
        public Nullable<byte> CompID { get; set; }
        public Nullable<byte> UIDAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> UIDMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
    }
}
