//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public int ID { get; set; }
        public Nullable<int> ScheduleId { get; set; }
        public byte SessionId { get; set; }
        public int ClassId { get; set; }
        public Nullable<int> MonFID { get; set; }
        public Nullable<int> MonSID { get; set; }
        public Nullable<int> TueFID { get; set; }
        public Nullable<int> TueSID { get; set; }
        public Nullable<int> WedFID { get; set; }
        public Nullable<int> WedSID { get; set; }
        public Nullable<int> ThuFID { get; set; }
        public Nullable<int> ThuSID { get; set; }
        public Nullable<int> FriFID { get; set; }
        public Nullable<int> FriSID { get; set; }
        public Nullable<int> SatFID { get; set; }
        public Nullable<int> SatSID { get; set; }
        public Nullable<byte> UIDAdd { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<byte> UIDMod { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
    }
}
