//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLogin
    {
        public int UserID { get; set; }
        public string FullName { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> RoleId { get; set; }
        public Nullable<bool> IsAdmin { get; set; }
        public byte[] AppImage { get; set; }
        public string AppImageName { get; set; }
        public string ThemesName { get; set; }
        public int BranchID { get; set; }
        public int CompID { get; set; }
        public string MobileNo { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> UserRoleWiseID { get; set; }
    }
}
