
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace appSchool.Repositories
{

using System;
    using System.Collections.Generic;
    
public partial class vAccountFee
{

    public int FeesCategoryID { get; set; }

    public Nullable<int> Expr1 { get; set; }

    public Nullable<long> TransactionID { get; set; }

    public int AcCode { get; set; }

    public string Name { get; set; }

    public string Address { get; set; }

    public string City { get; set; }

    public string Pin { get; set; }

    public string Phone1 { get; set; }

    public string Phone2 { get; set; }

    public string Mobile1 { get; set; }

    public string Mobile2 { get; set; }

    public string Email { get; set; }

    public Nullable<decimal> OpBalance { get; set; }

    public Nullable<decimal> DrAmount { get; set; }

    public Nullable<decimal> CrAmount { get; set; }

    public Nullable<decimal> Balance { get; set; }

    public Nullable<System.DateTime> CreateDate { get; set; }

    public string PanNo { get; set; }

}

}
