//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vAndroidLoginByStudentDetail
    {
        public int ID { get; set; }
        public string FullName { get; set; }
        public string ModelNo { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> CompID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string MANUFACTURER { get; set; }
        public string DeviceID { get; set; }
        public string SerialNo { get; set; }
        public string Device { get; set; }
        public string IMSI { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> InstallDate { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
        public Nullable<System.DateTime> InstalModDate { get; set; }
        public bool ISLoggedin { get; set; }
        public string uniqueID { get; set; }
        public string androidId { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> LoginType { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string FatherName { get; set; }
        public string SMSMobileNo { get; set; }
        public string EnrollmentNo { get; set; }
    }
}
