//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBookIssueSubmitDetail
    {
        public int IssueID { get; set; }
        public Nullable<int> BookID { get; set; }
        public Nullable<int> AccessionID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public string MemberType { get; set; }
        public Nullable<System.DateTime> IssueDate { get; set; }
        public Nullable<bool> IsSubmitted { get; set; }
        public Nullable<System.DateTime> SubmitDate { get; set; }
        public Nullable<int> Fine { get; set; }
        public string Remark { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
        public string BookTitle { get; set; }
        public Nullable<int> BookNo { get; set; }
        public Nullable<int> PublishYear { get; set; }
        public string Edition { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<bool> IsDamaged { get; set; }
        public Nullable<int> ShelfId { get; set; }
        public Nullable<int> RackId { get; set; }
        public Nullable<bool> IsLost { get; set; }
        public Nullable<bool> Issuable { get; set; }
    }
}
