//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBookLostList
    {
        public string BookTitle { get; set; }
        public string AccessionNo { get; set; }
        public string Publisher { get; set; }
        public int BookId { get; set; }
        public Nullable<bool> IsLost { get; set; }
        public Nullable<int> LostBy { get; set; }
        public Nullable<System.DateTime> LostDate { get; set; }
        public string LostRemark { get; set; }
        public string MemberType { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
    }
}
