//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vBookMasterDetailList
    {
        public int BookId { get; set; }
        public int AccessionId { get; set; }
        public string AccessionNo { get; set; }
        public string BookTitle { get; set; }
        public string Author1 { get; set; }
        public string Author2 { get; set; }
        public string Author3 { get; set; }
        public string Author4 { get; set; }
        public string GrantedBy { get; set; }
        public string Publisher { get; set; }
        public Nullable<int> Volume { get; set; }
        public string Medium { get; set; }
        public string Source { get; set; }
        public string WebUrl { get; set; }
        public string ISBNNo { get; set; }
        public string ISSNNo { get; set; }
        public string ClassificationNo { get; set; }
        public string Subject { get; set; }
        public Nullable<int> BookNo { get; set; }
        public string Edition { get; set; }
        public Nullable<int> PublishYear { get; set; }
        public Nullable<int> Pages { get; set; }
        public Nullable<decimal> Price { get; set; }
        public byte[] FrontCover { get; set; }
        public string BillNo { get; set; }
        public Nullable<System.DateTime> BillDate { get; set; }
        public Nullable<int> ShelfId { get; set; }
        public Nullable<int> RackId { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<bool> Issuable { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
        public Nullable<bool> IsDamaged { get; set; }
        public Nullable<bool> IsLost { get; set; }
        public string MemberType { get; set; }
        public string CallNo { get; set; }
        public string FrontCoverImage { get; set; }
    }
}
