//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClassSetupReport
    {
        public int ClassSetupID { get; set; }
        public string ClassDescription { get; set; }
        public int ClassID { get; set; }
        public Nullable<int> ClassCategoryID { get; set; }
        public int SectionID { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<System.DateTime> Description { get; set; }
        public Nullable<byte> ClassCategoryName { get; set; }
        public Nullable<System.DateTime> SectionName { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public Nullable<byte> CompID { get; set; }
        public Nullable<byte> BranchID { get; set; }
        public string ClassName { get; set; }
        public string Expr1 { get; set; }
        public string Expr2 { get; set; }
        public string Expr3 { get; set; }
    }
}
