//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class VClassStrength
    {
        public string ClassName { get; set; }
        public string ClassDescription { get; set; }
        public int ClassSetupID { get; set; }
        public Nullable<int> TotalStudent { get; set; }
        public int SessionID { get; set; }
        public Nullable<byte> CompID { get; set; }
        public Nullable<byte> BranchID { get; set; }
    }
}
