//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vClassSyllabusSubjectwise
    {
        public int ClassSyllabusID { get; set; }
        public int ClassID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public int SubjectIDL1 { get; set; }
        public string PreferredBooks { get; set; }
        public int ID { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string Topic { get; set; }
        public string SubjectUnit { get; set; }
        public string Description { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
    }
}
