
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace appSchool.Repositories
{

using System;
    using System.Collections.Generic;
    
public partial class vEmployeeWorkingDaysdetail1
{

    public string EmplyeeName { get; set; }

    public int EmpID { get; set; }

    public int ML { get; set; }

    public int CL { get; set; }

    public int EL { get; set; }

    public int HPL { get; set; }

    public int WorkingDays { get; set; }

    public int PresentDays { get; set; }

    public int HolyDays { get; set; }

    public int AbsentDays { get; set; }

    public int LeaveDays { get; set; }

    public int OPL { get; set; }

    public int LWP { get; set; }

    public string Remark { get; set; }

    public string MobileNo { get; set; }

    public string Gender { get; set; }

    public Nullable<int> TransID { get; set; }

    public Nullable<byte> CompID { get; set; }

    public Nullable<byte> BranchID { get; set; }

    public Nullable<int> SessionID { get; set; }

    public Nullable<int> MonthID { get; set; }

    public Nullable<int> YearID { get; set; }

}

}
