
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace appSchool.Repositories
{

using System;
    using System.Collections.Generic;
    
public partial class vEmployeeLeaveQuota1
{

    public Nullable<int> ML { get; set; }

    public Nullable<int> CL { get; set; }

    public Nullable<int> EL { get; set; }

    public Nullable<int> HPL { get; set; }

    public Nullable<int> OPL { get; set; }

    public int TeacherID { get; set; }

    public string FirstName { get; set; }

    public string LastName { get; set; }

    public string Gender { get; set; }

    public byte CompID { get; set; }

    public byte BranchID { get; set; }

    public Nullable<int> SessionID { get; set; }

}

}
