//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vExamRemarkEntry
    {
        public Nullable<int> RollNo { get; set; }
        public string FullName { get; set; }
        public int StudentID { get; set; }
        public string TeacherRemark { get; set; }
        public string PrincipalRemark { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public int AttendanceTotal { get; set; }
        public int AttendancePresent { get; set; }
    }
}
