
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace appSchool.Repositories
{

using System;
    using System.Collections.Generic;
    
public partial class vEXamSetUpTransfer1
{

    public int ExamSetupID { get; set; }

    public Nullable<int> ExamID { get; set; }

    public int ClassID { get; set; }

    public string ClassName { get; set; }

    public string ExamName { get; set; }

    public Nullable<bool> IsTransfer { get; set; }

    public byte CompID { get; set; }

    public byte BranchID { get; set; }

    public Nullable<int> SessionID { get; set; }

}

}
