//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vExamMarkEntry
    {
        public Nullable<int> RollNo { get; set; }
        public string FullName { get; set; }
        public int StudentID { get; set; }
        public string ObtainMark { get; set; }
        public int MinMark { get; set; }
        public int MaxMark { get; set; }
        public Nullable<bool> IsAbsent { get; set; }
    }
}
