//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vFeesStructureOldStudent
    {
        public Nullable<int> ClassId { get; set; }
        public Nullable<int> TermId { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
        public Nullable<int> FeeStructSessionID { get; set; }
    }
}
