//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vHomePageUserPermission
    {
        public int HomePageID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public int ModuleID { get; set; }
        public int FeatureID { get; set; }
        public bool CanView { get; set; }
        public int FeatureOrder { get; set; }
        public int CompID { get; set; }
        public int BranchID { get; set; }
        public string MModuleName { get; set; }
        public string MMenuText { get; set; }
        public string MMenuIcon { get; set; }
        public Nullable<int> MModuleCode { get; set; }
        public string MFeatureName { get; set; }
        public string FMenuText { get; set; }
        public string FMenuIcon { get; set; }
        public string FBgColor1 { get; set; }
        public string FBgColor2 { get; set; }
        public string FNavUrl { get; set; }
        public Nullable<int> FeatureCode { get; set; }
        public string MNavUrl { get; set; }
        public bool IsOnlyModuleRequire { get; set; }
    }
}
