//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_ClassSetup
    {
        public string ClassDescription { get; set; }
        public string ClassName { get; set; }
        public string SectionName { get; set; }
        public string ClassCategoryName { get; set; }
        public Nullable<int> DisplayOrder { get; set; }
        public int ClassSetupID { get; set; }
        public int ClassID { get; set; }
        public Nullable<int> ClassCategoryID { get; set; }
        public int SectionID { get; set; }
    }
}
