//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSessionwiseAdmission
    {
        public Nullable<int> TotalStudent { get; set; }
        public string Gender { get; set; }
        public string SessionName { get; set; }
        public Nullable<int> SessionID { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
    }
}
