//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSMSTtmplate
    {
        public Nullable<long> RowID { get; set; }
        public int SMSTypeID { get; set; }
        public string SMSTypeName { get; set; }
        public int TemplateID { get; set; }
        public string TemplateName { get; set; }
    }
}
