//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSMSLogDataExport
    {
        public int SMSLogID { get; set; }
        public Nullable<System.DateTime> SentDateTime { get; set; }
        public string SMSText { get; set; }
        public string SMSMobileNo { get; set; }
        public Nullable<int> OrderBy { get; set; }
        public int SMSDetailID { get; set; }
        public int StudentID { get; set; }
        public int SessionID { get; set; }
        public string EnrollmentNo { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Nationality { get; set; }
        public string Religion { get; set; }
        public string FatherName { get; set; }
        public string StudentMobileNo { get; set; }
        public string SMSModal { get; set; }
        public int ClassSetupID { get; set; }
        public Nullable<int> HouseID { get; set; }
        public string ClassDescription { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
        public string MobileNo { get; set; }
        public string SMSTextStudent { get; set; }
    }
}
