//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vStudentReportDetail
    {
        public int StudentID { get; set; }
        public string EnrollmentNo { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string Nationality { get; set; }
        public string LocalAddress { get; set; }
        public string ParmanentAddress { get; set; }
        public string BloodGroup { get; set; }
        public string Religion { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public string EmailID { get; set; }
        public string SMSMobileNo { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public byte[] AppImage { get; set; }
    }
}
