//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vStudentExamResult
    {
        public int ID { get; set; }
        public int StudentID { get; set; }
        public int SessionID { get; set; }
        public int ClassID { get; set; }
        public int SubjectIDL1 { get; set; }
        public int SubjectIDL2 { get; set; }
        public int SubjectIDL3 { get; set; }
        public Nullable<bool> IsAbsent { get; set; }
        public string Grade { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
        public Nullable<int> RollNo { get; set; }
        public int ClassSetupID { get; set; }
        public string ClassDescription { get; set; }
        public string FullName { get; set; }
        public string EnrollmentNo { get; set; }
        public string SubjectCodeL1 { get; set; }
        public string SubjectNameL1 { get; set; }
        public string SubjectCodeL2 { get; set; }
        public string SubjectNameL2 { get; set; }
        public string SubjectCodeL3 { get; set; }
        public string SubjectNameL3 { get; set; }
    }
}
