//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vStudentLoginDetail
    {
        public int StudentID { get; set; }
        public int StudentLoginID { get; set; }
        public string FullName { get; set; }
        public string EnrollmentNo { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string City { get; set; }
        public string FatherName { get; set; }
        public string EmailID { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
        public string StudentUserName { get; set; }
        public string Password { get; set; }
        public Nullable<int> parentID { get; set; }
        public string ICardNo { get; set; }
        public string Gender { get; set; }
        public string LocalAddress { get; set; }
        public string ParmanentAddress { get; set; }
        public string FatherMobileNo { get; set; }
        public string FatherEmailID { get; set; }
        public string SMSMobileNo { get; set; }
        public int SessionID { get; set; }
        public int ClassID { get; set; }
        public int ClassSetupID { get; set; }
    }
}
