//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vStudentFeeReceiptPrint
    {
        public int TransactionID { get; set; }
        public int SessionID { get; set; }
        public long ReceiptNo { get; set; }
        public Nullable<System.DateTime> ReceiptDate { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> TermID { get; set; }
        public Nullable<decimal> FinalTotal { get; set; }
        public string Mode { get; set; }
        public string BankName { get; set; }
        public string BranchName { get; set; }
        public string ChequeNo { get; set; }
        public string ChequeDate { get; set; }
        public Nullable<System.DateTime> Remark { get; set; }
        public string VoucherNo { get; set; }
        public Nullable<long> UIDAdd { get; set; }
        public Nullable<byte> AddDate { get; set; }
        public Nullable<System.DateTime> UIDMod { get; set; }
        public Nullable<byte> ModDate { get; set; }
        public Nullable<System.DateTime> TermTotal { get; set; }
        public Nullable<decimal> FineAmount { get; set; }
        public Nullable<decimal> OtherAmount { get; set; }
        public Nullable<decimal> DiscountAmount { get; set; }
        public string DiscountType { get; set; }
        public Nullable<decimal> DiscountPercent { get; set; }
        public string FeeTermID { get; set; }
        public Nullable<decimal> FeesHeadID { get; set; }
        public string Amount { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public Nullable<int> BankCode { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
        public Nullable<int> Expr1 { get; set; }
        public Nullable<int> Expr2 { get; set; }
        public Nullable<decimal> Expr3 { get; set; }
    }
}
