//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vStudentSession
    {
        public int StudentSessionID { get; set; }
        public int SessionID { get; set; }
        public int StudentID { get; set; }
        public string EnrollmentNo { get; set; }
        public string FullName { get; set; }
        public int ClassSetupID { get; set; }
        public string ClassDescription { get; set; }
        public Nullable<int> HouseID { get; set; }
        public string HouseName { get; set; }
        public Nullable<int> BusID { get; set; }
        public string BusName { get; set; }
        public string SMSMobileNo { get; set; }
        public int ClassID { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string FatherName { get; set; }
        public string Religion { get; set; }
        public Nullable<int> HouseColor { get; set; }
        public Nullable<int> RollNo { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
        public string Caste { get; set; }
        public bool IsNewStudent { get; set; }
        public bool FeesStructStatus { get; set; }
        public bool BusFacility { get; set; }
        public bool SMSInHindi { get; set; }
        public bool IsTransfered { get; set; }
        public bool HostelFacility { get; set; }
        public Nullable<bool> TCGiven { get; set; }
        public Nullable<bool> EnableSMSFeature { get; set; }
    }
}
