//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vStudentAllSessiondetail
    {
        public int StudentID { get; set; }
        public string FullName { get; set; }
        public string Gender { get; set; }
        public string ClassName { get; set; }
        public string SessionName { get; set; }
        public int SessionID { get; set; }
        public string ClassDescription { get; set; }
        public int ClassID { get; set; }
        public int ClassSetupID { get; set; }
        public string EnrollmentNo { get; set; }
        public string FatherName { get; set; }
        public string SMSMobileNo { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
    }
}
