//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vStudentFee
    {
        public int FeeTermID { get; set; }
        public string Term { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string DueDate { get; set; }
        public bool PaidFlag { get; set; }
        public string PaidStatus { get; set; }
        public bool Expr1 { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public string MobileNo { get; set; }
        public Nullable<int> EReceiptno { get; set; }
        public Nullable<decimal> FineAmount { get; set; }
    }
}
