//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vStudentParentLogin
    {
        public int StudentID { get; set; }
        public string EnrollmentNo { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public Nullable<System.DateTime> DateOfBirth { get; set; }
        public string FatherName { get; set; }
        public string MotherName { get; set; }
        public Nullable<System.DateTime> FatherDOB { get; set; }
        public Nullable<System.DateTime> MotherDOB { get; set; }
        public Nullable<int> SessionID { get; set; }
        public string StudentLoginID { get; set; }
        public string StudentPassword { get; set; }
        public string ParentLoginId { get; set; }
        public string ParentPassword { get; set; }
        public byte CompID { get; set; }
        public byte BranchID { get; set; }
    }
}
