//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSubjectAllotmentwithIDLThree
    {
        public int IdL1 { get; set; }
        public string SubjectCodeL1 { get; set; }
        public string SubjectNameL1 { get; set; }
        public Nullable<int> Order1 { get; set; }
        public int IdL2 { get; set; }
        public string SubjectCodeL2 { get; set; }
        public string SubjectNameL2 { get; set; }
        public Nullable<int> Order2 { get; set; }
        public int IdL3 { get; set; }
        public string SubjectCodeL3 { get; set; }
        public string SubjectNameL3 { get; set; }
        public Nullable<int> Order3 { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
    }
}
