//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vSubjectAllotmentDataExport
    {
        public int ClassID { get; set; }
        public int IDL1 { get; set; }
        public int IDL2 { get; set; }
        public int IDL3 { get; set; }
        public string ClassName { get; set; }
        public string SubjectNameL1 { get; set; }
        public string SubjectNameL2 { get; set; }
        public string SubjectNameL3 { get; set; }
    }
}
