//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTeacherLoginDetail
    {
        public int TeacherID { get; set; }
        public int Expr1 { get; set; }
        public string FullName { get; set; }
        public int TeacherLoginID { get; set; }
        public string TeacherUserName { get; set; }
        public string Password { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string FatherName { get; set; }
        public string MobileNo { get; set; }
    }
}
