//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTeacherForLoginID
    {
        public int TeacherID { get; set; }
        public string EmployeeCode { get; set; }
        public Nullable<System.DateTime> DOJ { get; set; }
        public string MobileNo { get; set; }
        public string ParmanentAddress { get; set; }
        public string LocalAddress { get; set; }
        public string EmailID { get; set; }
        public Nullable<int> DesignationId { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public byte[] AppImage { get; set; }
        public string FullName { get; set; }
    }
}
