//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTeacherBirthDay
    {
        public int TeacherID { get; set; }
        public string FULLNAME { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public string MobileNo { get; set; }
        public string Gender { get; set; }
        public string EmployeeCode { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
    }
}
