//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vTermListFromStudFeeMaster
    {
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> TermID { get; set; }
        public string FeeTermName { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public Nullable<decimal> DueAmount { get; set; }
        public string FeeTermType { get; set; }
        public int StudmasterID { get; set; }
        public byte BranchID { get; set; }
        public byte CompID { get; set; }
    }
}
