//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class vUserRoleModulePermission
    {
        public int Id { get; set; }
        public int RoleId { get; set; }
        public int ModuleId { get; set; }
        public int FeatureId { get; set; }
        public int FeatureIndex { get; set; }
        public bool CanAdd { get; set; }
        public bool CanEdit { get; set; }
        public bool CanDelete { get; set; }
        public bool CanView { get; set; }
        public Nullable<byte> UIDAdd { get; set; }
        public Nullable<byte> CompID { get; set; }
        public Nullable<byte> BranchID { get; set; }
        public string MMenuText { get; set; }
        public string MMenuIcon { get; set; }
        public string MBgColor1 { get; set; }
        public string MBgColor2 { get; set; }
        public Nullable<int> MasterFeatureId { get; set; }
        public string FName { get; set; }
        public string FMenuText { get; set; }
        public string FMenuIcon { get; set; }
        public string FBgColor1 { get; set; }
        public string FBgColor2 { get; set; }
        public string FNavUrl { get; set; }
    }
}
