//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace appSchool.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZoomMetting
    {
        public int ZoomID { get; set; }
        public Nullable<int> StudentID { get; set; }
        public Nullable<int> ClassID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<int> CompID { get; set; }
        public Nullable<int> BranchID { get; set; }
        public string MettingID { get; set; }
        public string EndTime { get; set; }
        public string StartTime { get; set; }
        public Nullable<int> TeacherID { get; set; }
        public Nullable<int> IdL1 { get; set; }
        public Nullable<int> ClassSetupID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public string ZoomPassword { get; set; }
        public Nullable<System.DateTime> AddDate { get; set; }
        public Nullable<System.DateTime> ModDate { get; set; }
    }
}
